[package]
name = "actix-web-httpauth"
version = "0.3.2"
authors = ["svartalf <self@svartalf.info>"]
description = "HTTP authentication schemes for actix-web"
readme = "README.md"
keywords = ["http", "web", "framework"]
homepage = "https://github.com/svartalf/actix-web-httpauth"
repository = "https://github.com/svartalf/actix-web-httpauth.git"
documentation = "https://docs.rs/actix-web-httpauth/"
categories = ["web-programming::http-server"]
license = "MIT OR Apache-2.0"
exclude = [".travis.yml", ".gitignore"]
edition = "2018"

[dependencies]
actix-web = { version = "^2.0", default_features = false }
actix-service = "1.0"
futures = "0.3"
bytes = "0.4"
base64 = "0.10"

[dev-dependencies]
actix-rt = "1.0"

[features]
default = []
nightly = []

[badges]
travis-ci = { repository = "svartalf/actix-web-httpauth", branch = "master" }
maintenance = { status = "passively-maintained" }
